name: Update Documentation
on:
  workflow_dispatch:
    inputs:
      ignite-branch:
        description: 'The released Ignite branch (e.g. ignite-2.12)'
        required: true
      ignite-version:
        description: 'The released Ignite version (e.g. 2.12.0)'
        required: true
jobs:
  update-documentation:
    name: Update documentation for released Ignite versions
    runs-on: ubuntu-latest
    steps:
      - name: Check out 'ignite-website' repository code
        uses: actions/checkout@v3.0.2
      - name: Install prerequisites
        run: |
          sudo apt-get install ruby-full build-essential zlib1g-dev
          echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
          echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
          echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
          sudo chown -R $(whoami) /var/lib/gems/*
          gem install jekyll bundler
      - name: Build
        run: |
          cd ${{ github.workspace }}/_docs
          ./build.sh --version=2.11.0 --github-branch=ignite-2.11
      - name: Create branch and commit
        run: |
          git config --global user.email "<>"
          git config --global user.name "GitHub Actions Bot"
          cd ${{ github.workspace }}
          git checkout -b bot-update-docs-${{ github.event.inputs.ignite-version }}
          git commit -a -m "[bot] Update ${{ github.event.inputs.ignite-version }} documentation."
          git push origin bot-update-docs-${{ github.event.inputs.ignite-version }}
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: '[bot] Update ${{ github.event.inputs.ignite-version }} documentation.',
              owner,
              repo,
              head: 'bot-update-docs-${{ github.event.inputs.ignite-version }}',
              base: 'master',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['bot']
            });